# Generated by Django 5.2 on 2025-05-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit_empleador', models.CharField(max_length=13, verbose_name='CUIT del empleador')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del establecimiento')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('localidad', models.CharField(max_length=100, verbose_name='Localidad')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia')),
                ('codigo_postal', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('tipo_establecimiento', models.CharField(max_length=100, verbose_name='Tipo de establecimiento')),
                ('actividad_clae', models.CharField(max_length=10, verbose_name='Código CLAE')),
                ('descripcion_actividad', models.TextField(verbose_name='Descripción de la actividad')),
                ('cantidad_trabajadores', models.PositiveIntegerField(verbose_name='Cantidad de trabajadores')),
                ('turnos', models.CharField(max_length=100, verbose_name='Turnos de trabajo')),
                ('trabajo_nocturno', models.BooleanField(verbose_name='¿Hay trabajo nocturno?')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
        ),
    ]
