# Generated by Django 5.2 on 2025-05-15 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIIU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(max_length=11, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('tipo_organismo', models.IntegerField()),
                ('organismo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='establecimiento',
            name='actividad_clae',
        ),
        migrations.RemoveField(
            model_name='establecimiento',
            name='cantidad_trabajadores',
        ),
        migrations.RemoveField(
            model_name='establecimiento',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='establecimiento',
            name='cuit_empleador',
        ),
        migrations.RemoveField(
            model_name='establecimiento',
            name='descripcion_actividad',
        ),
        migrations.RemoveField(
            model_name='establecimiento',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='establecimiento',
            name='email',
        ),
        migrations.RemoveField(
            model_name='establecimiento',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='establecimiento',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='establecimiento',
            name='trabajo_nocturno',
        ),
        migrations.RemoveField(
            model_name='establecimiento',
            name='turnos',
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='calle',
            field=models.CharField(default='Sin calle', max_length=255),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='cp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='cpa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='cuit',
            field=models.CharField(default='00000000000', max_length=11),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='descripcion',
            field=models.TextField(default='Sin nombre'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='dpto',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='interseccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='localidad_nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='motivo_baja',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='numero_establecimiento',
            field=models.IntegerField(default='0000'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='organismo',
            field=models.IntegerField(default='0000'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='piso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='principal',
            field=models.BooleanField(default='0'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='provincia_nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='temporal',
            field=models.BooleanField(default='0'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='tipo_organismo',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='tipo_establecimiento',
            field=models.SmallIntegerField(),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='establecimientos.empresa'),
        ),
        migrations.CreateModel(
            name='EstablecimientoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(max_length=11)),
                ('propio', models.BooleanField()),
                ('fecha_inicio_actividad', models.DateTimeField()),
                ('fecha_fin_actividad', models.DateTimeField()),
                ('tipo_organismo', models.IntegerField()),
                ('organismo', models.IntegerField()),
                ('motivo_baja', models.IntegerField(blank=True, null=True)),
                ('ciiu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='establecimientos.ciiu')),
            ],
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='establecimientos.localidad'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimientos.provincia'),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='establecimientos.provincia'),
        ),
    ]
