# Generated by Django 5.2 on 2025-05-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0002_ciiu_empresa_localidad_provincia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='codigo',
            field=models.BigIntegerField(unique=True),
        ),
    ]
