# Generated by Django 5.2 on 2025-05-15 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0003_alter_localidad_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPostal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp', models.CharField(max_length=10)),
                ('cpa', models.CharField(blank=True, max_length=10, null=True)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='establecimientos.localidad')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='establecimientos.provincia')),
            ],
            options={
                'unique_together': {('provincia', 'localidad', 'cp')},
            },
        ),
    ]
