# Generated by Django 5.2 on 2025-05-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0004_codigopostal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadCLAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
    ]
