# Generated by Django 5.2 on 2025-05-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0006_alter_actividadclae_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadclae',
            name='descripcion',
            field=models.CharField(max_length=1024),
        ),
    ]
