# Generated by Django 5.2 on 2025-05-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0007_alter_actividadclae_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadclae',
            name='clae2',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='actividadclae',
            name='clae2_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividadclae',
            name='clae3',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='actividadclae',
            name='clae3_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividadclae',
            name='letra',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='actividadclae',
            name='letra_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividadclae',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
