# Generated by Django 5.2 on 2025-05-23 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0008_actividadclae_clae2_actividadclae_clae2_desc_and_more'),
        ('ubicaciones', '0002_actividadclae'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='razon_social',
            new_name='nombre_fantasia',
        ),
        migrations.AddField(
            model_name='empresa',
            name='claes',
            field=models.ManyToManyField(blank=True, related_name='empresas', to='establecimientos.actividadclae'),
        ),
        migrations.AddField(
            model_name='establecimientoempresa',
            name='clae',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ubicaciones.actividadclae'),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='numero_establecimiento',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='organismo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='temporal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='tipo_organismo',
            field=models.IntegerField(default=0),
        ),
    ]
